apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gateway/deployment.yaml
- gateway/service.yaml
- gateway/ingress.yaml
- user-service/deployment.yaml
- user-service/service.yaml
- integration-service/deployment.yaml
- integration-service/service.yaml
- ai-router-service/deployment.yaml
- ai-router-service/service.yaml
- briefing-service/deployment.yaml
- briefing-service/service.yaml
- frontend/deployment.yaml
- frontend/service.yaml

images:
- name: ghcr.io/parkhyeonbeom/workcopilot-ai-router-service
  newName: ghcr.io/parkhyeonbeom/workcopilot-ai-router-service
  newTag: 8b04569
- name: ghcr.io/parkhyeonbeom/workcopilot-briefing-service
  newName: ghcr.io/parkhyeonbeom/workcopilot-briefing-service
  newTag: 8b04569
- name: ghcr.io/parkhyeonbeom/workcopilot-frontend
  newName: ghcr.io/parkhyeonbeom/workcopilot-frontend
  newTag: 8b04569
- name: ghcr.io/parkhyeonbeom/workcopilot-gateway
  newName: ghcr.io/parkhyeonbeom/workcopilot-gateway
  newTag: 8b04569
- name: ghcr.io/parkhyeonbeom/workcopilot-integration-service
  newName: ghcr.io/parkhyeonbeom/workcopilot-integration-service
  newTag: 8b04569
- name: ghcr.io/parkhyeonbeom/workcopilot-user-service
  newName: ghcr.io/parkhyeonbeom/workcopilot-user-service
  newTag: 8b04569
